apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuaWNrLmthdGFmb2xAZ21haWwuY29tIiwicGFzc3dvcmQiOiI1NDg2NTU2MThaekAiLCJhdXRoIjoiYm1samF5NXJZWFJoWm05c1FHZHRZV2xzTG1OdmJUbzFORGcyTlRVMk1UaGFla0E9In19fQ==
kind: Secret
metadata:
  name: my-registry-key
  namespace: default
type: kubernetes.io/dockerconfigjson
