apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuaWNrLmthdGFmb2xAZ21haWwuY29tIiwicGFzc3dvcmQiOiI1NDg2NTU2MThaekAiLCJhdXRoIjoiYm1samF5NXJZWFJoWm05c1FHZHRZV2xzTG1OdmJUbzFORGcyTlRVMk1UaGFla0E9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2025-04-20T23:36:26Z"
  name: my-registry-key
  namespace: default
  resourceVersion: "612492"
  uid: 48ff54a7-b170-4900-8ef0-2ce01ed8fdc6
type: kubernetes.io/dockerconfigjson
