apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo
  name: todo-svc
  namespace: default
spec:
  ports:
  - nodePort: 31670
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: todo
  type: NodePort

  
